"""
* EmotionalModule (manages the marionette's emotional state) [Kaz/Steph]
  - Maintains a geometric structure representing the emotional state
  - Applies reactions generated by the Reactors to that state
  - Updates the state over time (as strong emotions naturally fade)
  - Triggers Actions (as determined by strong emotional states)
  - [Optional] May apply modifiers to parameters of all actions (i.e. sadness makes movements slower)
"""

class EmotionModule(object):

	def __init__(self,config,response_module):
		pass
