#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Sat Jul 21 22:33:01 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

import ArduinoCommunicator


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
    
        self.ac = ArduinoCommunicator.ArduinoCommunicator()
        self.label_list = []
        self.up_btn_list = []
        self.down_btn_list = []
        self.slider_list = []
        self.sizer_list = []


        
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((839, 674))
        self.SetTitle("frame")
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.notebook_1_Steppers = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1_HeadandShoulderRotation = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1_Eyes = wx.Panel(self.notebook_1, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(0, 5, 10, 10)
        for name in self.ac.motor_name_list:
            
            label = wx.StaticText(self.notebook_1_Steppers, wx.ID_ANY, name, style=wx.ALIGN_CENTER)
            label.SetBackgroundColour(wx.Colour(255, 127, 0))
            label.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 1, ""))
            
            slider = wx.Slider(self.notebook_1_Steppers, wx.ID_ANY, 0, 0, 60, style=wx.SL_HORIZONTAL | wx.SL_LABELS)
            
            up_btn = wx.Button(self.notebook_1_Steppers, wx.ID_ANY, "Up")
            up_btn.SetFont(wx.Font(40, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
            up_btn.Bind(wx.EVT_LEFT_DOWN, self.onUpBtnDown)
            up_btn.Bind(wx.EVT_LEFT_UP, self.onUpBtnUp)
            
            down_btn = wx.Button(self.notebook_1_Steppers, wx.ID_ANY, "Down")
            down_btn.SetFont(wx.Font(40, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
            down_btn.Bind(wx.EVT_LEFT_DOWN, self.onDownBtnDown)
            down_btn.Bind(wx.EVT_LEFT_UP, self.onDownBtnUp)
            
            sizer = wx.BoxSizer(wx.VERTICAL)
            sizer.Add(label, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
            sizer.Add(slider, 0, wx.EXPAND, 0)
            sizer.Add(up_btn, 1, wx.EXPAND, 0)
            sizer.Add(down_btn, 1, wx.EXPAND, 0)
            
            grid_sizer_1.Add(sizer, 1, wx.EXPAND, 0)
            
            self.up_btn_list.append(up_btn)
            self.down_btn_list.append(down_btn)
            self.slider_list.append(slider)
            self.sizer_list.append(sizer)
            self.label_list.append(label)
        
        self.button_20 = wx.Button(self.notebook_1_Steppers, wx.ID_ANY, "STOP!!!")
        self.button_20.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.Bind(wx.EVT_BUTTON, self.onBtnStop, self.button_20)
        sizer_11.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_11.Add(self.button_20, 0, wx.EXPAND, 0)
        self.notebook_1_Steppers.SetSizer(sizer_11)
        self.notebook_1.AddPage(self.notebook_1_Steppers, "Steppers")
        
        self.notebook_1.AddPage(self.notebook_1_HeadandShoulderRotation, "Head and Shoulder Rotation")
        self.slider_20 = wx.Slider(self.notebook_1_HeadandShoulderRotation, wx.ID_ANY, 0, -50, 50, style=wx.SL_HORIZONTAL | wx.SL_LABELS)
        self.button_41 = wx.Button(self.notebook_1_HeadandShoulderRotation, wx.ID_ANY, "Move Head")
        self.Bind(wx.EVT_BUTTON, self.onMoveHead, self.button_41)
        self.slider_21 = wx.Slider(self.notebook_1_HeadandShoulderRotation, wx.ID_ANY, 0, -30, 30, style=wx.SL_HORIZONTAL | wx.SL_LABELS)
        self.button_42 = wx.Button(self.notebook_1_HeadandShoulderRotation, wx.ID_ANY, "Move Shoulder")
        self.Bind(wx.EVT_BUTTON, self.onMoveShoulder, self.button_42)
        self.slider_20.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_41.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.slider_21.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_42.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        label_20 = wx.StaticText(self.notebook_1_HeadandShoulderRotation, wx.ID_ANY, "Head Rotation", style=wx.ALIGN_CENTER)
        label_20.SetBackgroundColour(wx.Colour(255, 127, 0))
        label_20.SetFont(wx.Font(40, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 1, ""))
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_22.Add(label_20, 1, wx.EXPAND, 0)
        sizer_22.Add(self.slider_20, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)
        sizer_22.Add(self.button_41, 1, wx.EXPAND, 0)
        static_line_1 = wx.StaticLine(self.notebook_1_HeadandShoulderRotation, wx.ID_ANY)
        sizer_22.Add(static_line_1, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)
        label_21 = wx.StaticText(self.notebook_1_HeadandShoulderRotation, wx.ID_ANY, "Shoulder Rotation", style=wx.ALIGN_CENTER)
        label_21.SetBackgroundColour(wx.Colour(255, 127, 0))
        label_21.SetFont(wx.Font(40, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 1, ""))
        sizer_22.Add(label_21, 1, wx.EXPAND, 0)
        sizer_22.Add(self.slider_21, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)
        sizer_22.Add(self.button_42, 1, wx.EXPAND, 0)
        self.notebook_1_HeadandShoulderRotation.SetSizer(sizer_22)
        
        self.notebook_1.AddPage(self.notebook_1_Eyes, "Eyes")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        
       
    def findIdFromButton(self, btn_obj, up_or_down):
        if up_or_down == "up":
            return self.up_btn_list.index(btn_obj)
        if up_or_down == "down":
            return self.down_btn_list.index(btn_obj)
            
    def getSpeedById(self, id):
        return self.slider_list[id].GetValue()

    def onUpBtnUp(self, event):  # wxGlade: MyFrame.<event_handler>
        self.ac.stopAllSteppers()
        
    def onBtnStop(self, event):  # wxGlade: MyFrame.<event_handler>
        self.ac.stopAllSteppers()
        
    def onUpBtnDown(self, event):  # wxGlade: MyFrame.<event_handler>
        id = self.findIdFromButton(event.GetEventObject(), "up")
        speed = int(self.slider_list[id].GetValue())
        self.ac.motor_cmd_dict[self.ac.motor_name_list[id]] = -speed
        self.ac.move()
        
    def onDownBtnUp(self, event):  # wxGlade: MyFrame.<event_handler>
        self.ac.stopAllSteppers()
        
    def onDownBtnDown(self, event):  # wxGlade: MyFrame.<event_handler>
        id = self.findIdFromButton(event.GetEventObject(), "down")
        speed = int(self.slider_list[id].GetValue())
        self.ac.motor_cmd_dict[self.ac.motor_name_list[id]] = speed
        self.ac.move()
        
    def onMoveHead(self, event):
        pose = int(self.slider_20.GetValue())
        self.ac.rotateHead(pose)
    
    def onMoveShoulder(self, event):
        pose = int(self.slider_21.GetValue())
        self.ac.rotateShoulder(pose)

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
